In [1]:
import torch

In [3]:
x = torch.rand(3, requires_grad=True) # PyTorch constructs computational graph from which it will work out gradients
x

tensor([0.0558, 0.0546, 0.7019], requires_grad=True)

In [4]:
y = x + 2
print(y)

tensor([2.0558, 2.0546, 2.7019], grad_fn=<AddBackward0>)


In [5]:
z = y * y * 2
z

tensor([ 8.4527,  8.4430, 14.6004], grad_fn=<MulBackward0>)

In [6]:
z = z.mean()
z

tensor(10.4987, grad_fn=<MeanBackward0>)

In [7]:
z.backward() # calculate dz/dx
print(x.grad)

tensor([2.7411, 2.7395, 3.6025])


In [9]:
# whenever backward function called, gradient for tensor accumulated into grad attribute
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights * 3).sum()
    
    model_output.backward()
    
    print(weights.grad)
    
    weights.grad.zero_() # stops gradients accumulating in grad attirubute when backward is called

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
