In [15]:
import torch
import torch.nn as nn
import numpy as np

In [16]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

In [17]:
x = np.array([2.0, 1.0, 0.1])
outputs = softmax(x)
print('softmax numpy: ', outputs)

softmax numpy:  [0.65900114 0.24243297 0.09856589]


In [18]:
x = torch.tensor([2.0, 1.0, 0.1])
outputs = torch.softmax(x, dim=0)
print('softmax torch: ', outputs)

softmax torch:  tensor([0.6590, 0.2424, 0.0986])


In [19]:
def cross_entropy(actual, predicted):
    loss = -np.sum(actual * np.log(predicted))
    return loss

In [20]:
Y = np.array([1, 0, 0])

Y_pred_good = np.array([0.7, 0.2, 0.1])
Y_pred_bad = np.array([0.1, 0.3, 0.6])

l1 = cross_entropy(Y, Y_pred_good)
l2 = cross_entropy(Y, Y_pred_bad)

print("Loss 1: ", l1)
print("Loss 2: ", l2)

Loss 1:  0.35667494393873245
Loss 2:  2.3025850929940455


In [22]:
loss = nn.CrossEntropyLoss() # includes softmax, Y should be class labels

Y = torch.tensor([0])
# nsamples x nclasses = 1x3
Y_pred_good = torch.tensor([[2.0, 1.0, 0.1]]) # no softmax, raw values
Y_pred_bad = torch.tensor([[0.2, 1.0, 0.7]]) # no softmax, raw values

l1 = loss(Y_pred_good, Y)
l2 = loss(Y_pred_bad, Y)

print("Loss 1: ", l1.item())
print("Loss 2: ", l2.item())

Loss 1:  0.4170299470424652
Loss 2:  1.5839687585830688


In [23]:
_, preds_1 = torch.max(Y_pred_good, 1)
_, preds_2 = torch.max(Y_pred_bad, 1)

print(preds_1)
print(preds_2)

tensor([0])
tensor([1])


In [26]:
# multiple samples
Y = torch.tensor([2, 0, 1])

Y_pred_good = torch.tensor([[0.1, 1.0, 7.6], [2.0, 1.0, 0.1], [2.0, 7.0, 0.1]]) # no softmax, raw values

l1 = loss(Y_pred_good, Y)

print("Loss 1: ", l1)

Loss 1:  tensor(0.1422)


In [27]:
_, preds = torch.max(Y_pred_good, 1)
print(preds)

tensor([2, 0, 1])


In [31]:
# Use in Neural Network

# Multiclass problem
class NeuralNet(nn.Module):
    
    def __init__(self, input_size, hidden_size, num_classes):
        super().__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.Linear2 = nn.Linear(hidden_size, num_classes)
        
    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        # no softmax at end
        return out

In [32]:
model = NeuralNet(input_size=28*28, hidden_size=5, num_classes=3)
criterion = nn.CrossEntropyLoss() # applies softmax

In [33]:
# Binary Problem
class NeuralNet(nn.Module):
    
    def __init__(self, input_size, hidden_size):
        super().__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.Linear2 = nn.Linear(hidden_size, 1)
        
    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        y_pred = torch.sigmoid(out)
        return y_pred

In [34]:
model = NeuralNet(input_size=28*28, hidden_size=5)
criterion = nn.BCELoss()