In [1]:
import torch
import numpy as np

In [5]:
#create empty tensor
x = torch.empty(2, 3)
x

tensor([[4.2191e-08, 3.2771e-09, 1.3236e-08],
        [8.4713e-07, 8.2187e+20, 1.6705e+22]])

In [10]:
x = torch.rand(2, 2)
x

tensor([[0.7740, 0.4350],
        [0.4540, 0.3847]])

In [12]:
x = torch.zeros(2, 2)
x

tensor([[0., 0.],
        [0., 0.]])

In [13]:
x = torch.ones(2, 2)
x

tensor([[1., 1.],
        [1., 1.]])

In [14]:
x.dtype

torch.float32

In [15]:
x = torch.ones(2, 2, dtype=torch.int)
x.dtype

torch.int32

In [17]:
x.size()

torch.Size([2, 2])

In [18]:
# construct tensor from list
x = torch.tensor([0.25, 1])
x

tensor([0.2500, 1.0000])

In [20]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
z = x + y # element wise addition
z = torch.add(x, y) # same as above
print(z)

tensor([[0.2869, 0.2627],
        [0.0812, 0.6221]])
tensor([[0.4178, 0.6103],
        [0.3045, 0.8453]])
tensor([[0.7047, 0.8729],
        [0.3857, 1.4674]])


In [21]:
y.add_(x) # trailing underscore functions modify tensors in-place
y

tensor([[0.7047, 0.8729],
        [0.3857, 1.4674]])

In [23]:
z = x - y
z = x * y
z = x / y
z = torch.sub(x, y)
z = torch.mul(x, y)
z = torch.div(x, y)

In [25]:
x = torch.rand(5, 3)
x

tensor([[0.4926, 0.6437, 0.4794],
        [0.1664, 0.3858, 0.4302],
        [0.8521, 0.8034, 0.5565],
        [0.6331, 0.9804, 0.8078],
        [0.0558, 0.9807, 0.4363]])

In [34]:
# slicing tensors
print(x[:, 0]) # all rows, first col
print(x[1, :]) # 2nd row, all cols
print(x[1, 1])
print(x[1, 1].item()) # only if a single element

tensor([0.4926, 0.1664, 0.8521, 0.6331, 0.0558])
tensor([0.1664, 0.3858, 0.4302])
tensor(0.3858)
0.3857564926147461


In [36]:
# reshaping
x = torch.rand(4,4)
print(x)
y = x.view(16)
print(y)
y = x.view(-1, 8) # -1 to let pytorch automaticly work out dimension
print(y)

tensor([[0.4460, 0.8830, 0.2271, 0.5774],
        [0.4957, 0.0942, 0.8638, 0.5250],
        [0.3433, 0.8947, 0.2646, 0.5779],
        [0.7815, 0.9635, 0.9759, 0.7979]])
tensor([0.4460, 0.8830, 0.2271, 0.5774, 0.4957, 0.0942, 0.8638, 0.5250, 0.3433,
        0.8947, 0.2646, 0.5779, 0.7815, 0.9635, 0.9759, 0.7979])
tensor([[0.4460, 0.8830, 0.2271, 0.5774, 0.4957, 0.0942, 0.8638, 0.5250],
        [0.3433, 0.8947, 0.2646, 0.5779, 0.7815, 0.9635, 0.9759, 0.7979]])


In [41]:
# convert between torch and numpy
a = torch.ones(5)
b = a.numpy()
print(a)
print(type(a))
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [42]:
# if both tensors on cpu they share memory location
a.add_(1)
print(a)
print(b) # b also changes when a updated

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [43]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(type(a))
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>


In [45]:
# if both tensors on cpu they share memory location
a += 1
print(a)
print(b) # b also changes when a updated

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [48]:
# using gpu
if torch.cuda.is_available():
    device = torch.device('cuda')
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    print(z)
# numpy can only handle cpu tensors, not gpu

tensor([2., 2., 2., 2., 2.], device='cuda:0')
